# Generated by Django 2.2.6 on 2021-01-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsData', '0002_auto_20210117_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementtag',
            old_name='plant',
            new_name='site',
        ),
    ]
